name: Deploy App on kubernetes cluster
on: [workflow_dispatch]
jobs:
  deploy-testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker build action
      - name: Generate Tag
        run: echo "0.3.${{ github.run_number }}" >> $BUILD_IMAGE_TAG

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./flask_app
          tags: |
            ghcr.io/ojgenbar/flask-kube-x86:latest
            ghcr.io/ojgenbar/flask-kube-x86:0.3.{{ $BUILD_IMAGE_TAG }}
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - run: echo "🍏 This job's status is ${{ job.status }}."
